### ISSUE TITLE
threads parameter doesn't work

### ISSUE THREAD

**Issue by Microbion** [KennthShang/PhaMer#16]
Here's package version in conda environment:
![image](https://user-images.githubusercontent.com/35793183/229496270-644ef43f-71b1-4b01-a2ea-89d2fdbf5f95.png)
I runned phamer as follows:
```
python PhaMer_preprocessing.py --contigs my.fa --len 3000 --midfolder virus --threads 5
python PhaMer.py --midfolder virus --out pred.csv --threads 5
```
But actually more than 5 threads were used in script PhaMer.py.
The following code doesn't work:
```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device == "cpu":
    print("running with cpu")
    torch.set_num_threads(inputs.threads)
```
Then I tested these codes in python
![image](https://user-images.githubusercontent.com/35793183/229500418-819cbafb-0cf8-4532-8d4b-daa209a3fe6b.png)

**Comment by KennthShang** [comment]
Hi,

Thanks for using our tools.

You can change the code as :

```
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
if device.type == "cpu":
    print("running with cpu")
    torch.set_num_threads(inputs.threads)
```
I also revised the codes on GitHub accordingly.

Best,
Jiayu
