### ISSUE TITLE
No shebang line

### ISSUE THREAD

**Issue by schackartk** [KennthShang/PhaMer#2]
Your main program, `PhaMer.py` does not have a shebang line. As you know, programmers are lazy. I would love to be able to run your tool by simply typing:

```
./PhaMer.py --contigs input.fa
```

Instead of:

```
python3 PhaMer.py --contigs input.fa
```

Also, this would resolve issues regarding Python version. For instance, your usage example in the README.md says to run:

```
python PhaMer.py [--out OUTPUT_CSV] [--reject THRESHOLD]
```

However, this fails for me because `python` on my system points to Python 2. By adding a shebang, you could tell the system to run it with Python 3 without ambiguity.

**Comment by KennthShang** [comment]
Sorry for the inconvenience. 

Maybe we will add that function soon.

Best,
jiayu
