### ISSUE TITLE
Argparse documentation

### ISSUE THREAD

**Issue by schackartk** [KennthShang/PhaMer#3]
I believe your argparse documentation could be greatly improved to make it easier for the user to understand.

# Description

The description given in the argparse initialization: `argparse.ArgumentParser(description='manual to this script')` is supposed to describe the program itself. For instance it may be something like `argparse.ArgumentParser(description='Identify phage contigs from metagenome')`.

This is helpful because this description is seen when the user runs the `-h/--help` flag on your program (this is the beauty of arpgarse; you don't need to write any code to allow your program to have a built-in help flag). Here is what the user sees now.

```
$ python3 preprocessing.py -h
usage: PhaMer.py [-h] [--out OUT] [--reject REJECT]

manual to this script

optional arguments:
  -h, --help       show this help message and exit
  --out OUT
  --reject REJECT
```

# Argument descriptions

Each argument in your parser should have a help message to inform the user what that argument or option does. Having a metavar is also helpful to tell the user what kind of thing is being passed to the program. For example:

```
parser.add_argument('--contigs', help='FASTA file of contigs', metavar='FILE', type=str, default='test_contigs.fa')
```

Because as it is, it is very unclear what the arguments do.

**Comment by KennthShang** [comment]
Thanks for your suggestions.  We have revised them accordingly.
