### ISSUE TITLE
Cannot choose output for PhaMer.py

### ISSUE THREAD

**Issue by schackartk** [KennthShang/PhaMer#6]
Similar to #4 , you cannot specify the output directory for `PhaMer.py`. I tried to circumvent this by adding my own relative path to where I want the output file written:

```
$ python3 PhaMer.py --out foo/output.csv

...

FileNotFoundError: [Errno 2] No such file or directory: 'foo/out.csv'
```

Where there is a bunch of exception traceback messages where I put `...`.

This could be handled by with something along the lines of:
```
out_dir = os.path.dirname(inputs.out)

if not os.path.isdir(out_dir):
    os.makedirs(out_dir)
```

**Comment by KennthShang** [comment]
Thanks for your suggestions. We have add this function accordingly.

Best,
Jiayu
